# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 839867d81604ff9233bf99bb83b26cfa22f4002c7351e46547653535d9b37ec8b43a7e9b588a38eace447ee1e9ed33e933fc186e9308121608c98e0d58d11373

test:
  secret_key_base: db6f10e593be59277b8bc59a3a77b0a4d6c00a61cb252d0b1157040b80c38ee3b479b7c6151bd19463bc4d28d577de2e9f56639554b226e838d99a9bcd17709e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
